# Generated by Django 2.0.6 on 2018-06-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='date_created',
            new_name='created',
        ),
    ]
