# Generated by Django 2.0.6 on 2018-06-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180609_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
