# Generated by Django 2.0.6 on 2018-06-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180610_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
