# Generated by Django 2.0.6 on 2018-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180610_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
